### ISSUE TITLE
Change logo for dark and light background

### ISSUE THREAD

**Issue by benravetta** [eddiesigner/weiss-pro#10]
Hi Eddie,

Any idea how I can change the logo for a light background? My logo is light and almost entirely disappears on the white background, is there a way I can have a different logo display for the light theme?

Thank you

**Comment by eddiesigner** [comment]
Hi 👋🏻

Currently is not possible to upload two different logos in Ghost. What you can do is to apply a filter to the logo to invert the color.

You can paste this code into Code injection / Site Header in your Ghost Admin:

```html
<style>
.m-logo img {
  filter: invert(1);
}

[data-theme="light"] .m-logo img {
  filter: invert(1);
}

[data-theme="dark"] .m-logo img {
  filter: none;
}

@media (prefers-color-scheme: dark) {
  .m-logo img {
    filter: none;
  }

  [data-theme="light"] .m-logo img {
    filter: invert(1);
  }
}
</style>
```

**Comment by benravetta** [comment]
Hi Eddie,

Brilliant workaround! Thank you :)

Best Wishes,

Ben Ravetta | Company Director
brightwork.uk
Visit the forum community.
Need support? Open a ticket with us here.
This message is intended exclusively for the individual(s) to whom it is addressed and may contain information that is privileged, or confidential. If you are not the addressee, you must not read, use or disclose the contents of this e-mail. If you receive this e-mail in error, please advise us immediately and delete the e-mail. Brightwork have taken every reasonable precaution to ensure that any attachment to this e-mail has been swept for viruses. However, Brightwork cannot accept liability for any damage sustained as a result of software viruses and would advise that you carry out your own virus checks before opening any attachment.
