### ISSUE TITLE
How to enable the custom signin and signup pages?

### ISSUE THREAD

**Issue by jdhrivas** [eddiesigner/weiss-pro#15]
How to enable the custom member pages, signin, signup, account, and membership?

**Comment by eddiesigner** [comment]
Hi,

You can learn how to enable those pages in the docs: https://weiss-pro-docs.eduardogomez.io/guide/enable-members.html

Please read an follow all the steps carefully.

**Comment by jdhrivas** [comment]
Thanks! I totally missed that section.
