### ISSUE TITLE
Newsletter Block in post.hbs

### ISSUE THREAD

**Issue by uksitebuilder** [eddiesigner/weiss-pro#2]
Hi

Thanks for the recent updates.

Noticed in the post.hbs file that the Newsletter block is inside the Related Posts GET block

If the post being viewed has no related posts, the Newsletter block does not show (even if Members is enabled in admin)

**Comment by eddiesigner** [comment]
Thanks fort the heads up! I will fix it asap 😅

**Comment by eddiesigner** [comment]
It's fixed ;)
