### ISSUE TITLE
Enabling members feature confusion

### ISSUE THREAD

**Issue by kymellis** [eddiesigner/weiss-pro#7]
Hey Eddie! 

Kym here from the Ghost team 👋🏼

Since your Weiss Pro theme is so popular, I've noticed some customers getting confused about [enabling the members feature](https://github.com/eddiesigner/weiss-pro/wiki/How-to-enable-the-Members-feature). 

Some people thought they needed to add links to the navigation in Ghost Admin, rather than creating pages with the appropriate slugs. 

I just did a local install myself to figure out the answer - but I think it would be great to give more information and screenshots on your [wiki page](https://github.com/eddiesigner/weiss-pro/wiki/How-to-enable-the-Members-feature) about the members concepts that you've included in your theme. For example: 

- An explanation of the default behaviour of your theme (e.g. the Weiss Pro Theme supports both free and paid members by default, because the "sign up" page allows free member sign up)
- An explanation of what each page is and what they can be used for in the context of your theme (account, membership, newsletter)
- Clearer guidelines about creating actual pages inside Ghost vs adding links to the navigation

Would be happy to help review if you're able to update your wiki pages. I think it would prevent a lot of support requests for us both 🤗

**Comment by eddiesigner** [comment]
Hey Kym 👋🏻

Thank you for the suggestion, I already updated the [wiki page](https://github.com/eddiesigner/weiss-pro/wiki/How-to-enable-the-Members-feature) to include more descriptive and useful information about this, please take a look and let me know some feedback you might have so I can update the doc files as well.

Cheers.

**Comment by kymellis** [comment]
Hey Eddie, 

This is perfect - thanks for the speedy update :) I think Ghost users and people who purchase your theme will find this really helpful. 

FWIW we're working on a few things to make members implementation easier for everyone, so keep an eye out for future updates.

**Comment by eddiesigner** [comment]
Awesome! Looking forward to the members-related improvements :)
