### ISSUE TITLE
Gradient artefact visible when changing header colour.

### ISSUE THREAD

**Issue by benravetta** [eddiesigner/weiss-pro#9]
Hi Eddie,

I'm trying to change the header colour for light and dark toggle, could you help with this? When I check this out in inspector and change the CSS, an artefact appears. Please see the image. It looks like some sort of gradient.

<img width="342" alt="Screenshot 2020-06-16 at 03 09 49" src="https://user-images.githubusercontent.com/22097572/84724007-f20e8780-af7e-11ea-93ac-cf6318c6aa87.png">

Thanks again.

**Comment by eddiesigner** [comment]
Hi,

That gradient is there to make the overflow on that menu nicer. That overflow appears when you have multiple links in the main menu and the window width is not wider enough.

That gradient uses CSS variables so yu can change it easily, you just need to change the value of the variable `--header-menu-gradient-secound-color` with your desired color. Remember that you have to change it on both themes.

If you want to change it in the source code you can do it by modifying the file `/sass/common/_themes.scss`

You can also overwrite that value in the Ghost Admin like this:

```html
<style>
:root,
[data-theme="light"] {
  --header-menu-gradient-secound-color: YOUR_OWN_LIGHT_COLOR;
}

[data-theme="dark"] {
  --header-menu-gradient-secound-color: YOUR_OWN_DARK_COLOR;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --header-menu-gradient-secound-color: YOUR_OWN_DARK_COLOR;
  }    
}
</style>
```

Cheers.

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.
